/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Physical AI & Humanoid Robotics Textbook",
  "tagline": "Learn Humanoid Robotics Step by Step",
  "url": "http://localhost:3000",
  "baseUrl": "/",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "trailingSlash": false,
  "organizationName": "ZoyaAfzal",
  "projectName": "humanoid_robotic_book",
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "debug": {
          "debugMode": true,
          "lazyLoad": true
        },
        "docs": {
          "sidebarPath": "/mnt/d/Hackathon1/humanoid_robotic_book/sidebars.js"
        },
        "blog": {
          "showReadingTime": true
        },
        "theme": {
          "customCss": "/mnt/d/Hackathon1/humanoid_robotic_book/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "title": "Humanoid Robotics",
      "logo": {
        "alt": "Humanoid Robotics Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "mySidebar",
          "position": "left",
          "label": "Learn"
        },
        {
          "to": "/docs/intro",
          "label": "Getting Started",
          "position": "left"
        },
        {
          "type": "dropdown",
          "label": "Chapters",
          "position": "left",
          "items": [
            {
              "label": "Chapter 1: Spec-Kit Plus & Robotics Foundation",
              "to": "/docs/chapter1/lesson1/spec-kit-plus-workflow"
            },
            {
              "label": "Chapter 2: The Robotic Nervous System (ROS 2)",
              "to": "/docs/chapter2/lesson1/ros2-architecture"
            },
            {
              "label": "Chapter 3: The Digital Twin (Simulation)",
              "to": "/docs/chapter3/lesson1/gazebo-environment-setup"
            },
            {
              "label": "Chapter 4: The AI-Robot Brain (NVIDIA Isaac™)",
              "to": "/docs/chapter4/lesson1/isaac-sim-synthetic-data"
            },
            {
              "label": "Chapter 5: Vision-Language-Action (VLA) & Capstone",
              "to": "/docs/chapter5/lesson1/voice-to-action"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Resources",
          "position": "right",
          "items": [
            {
              "label": "Interactive Lessons",
              "to": "/docs/intro"
            },
            {
              "label": "ROS 2 Documentation",
              "href": "https://docs.ros.org/en/humble/"
            },
            {
              "label": "Simulation Guide",
              "to": "/docs/chapter3/lesson1/gazebo-environment-setup"
            }
          ]
        },
        {
          "type": "search",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
